# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gui(object):
    def setupUi(self, Gui):
        Gui.setObjectName("Gui")
        Gui.resize(280, 180)
        self.root = QtWidgets.QWidget(Gui)
        self.root.setObjectName("root")
        self.bt_Salvar = QtWidgets.QPushButton(self.root)
        self.bt_Salvar.setGeometry(QtCore.QRect(191, 135, 80, 25))
        self.bt_Salvar.setObjectName("bt_Salvar")
        self.bt_Sair = QtWidgets.QPushButton(self.root)
        self.bt_Sair.setGeometry(QtCore.QRect(100, 135, 80, 25))
        self.bt_Sair.setObjectName("bt_Sair")
        self.gBox_Config = QtWidgets.QGroupBox(self.root)
        self.gBox_Config.setGeometry(QtCore.QRect(9, 0, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gBox_Config.setFont(font)
        self.gBox_Config.setObjectName("gBox_Config")
        self.gBox_Ling = QtWidgets.QGroupBox(self.gBox_Config)
        self.gBox_Ling.setGeometry(QtCore.QRect(10, 20, 241, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.gBox_Ling.setFont(font)
        self.gBox_Ling.setFlat(True)
        self.gBox_Ling.setObjectName("gBox_Ling")
        self.rbt_PtBr = QtWidgets.QRadioButton(self.gBox_Ling)
        self.rbt_PtBr.setGeometry(QtCore.QRect(20, 25, 121, 18))
        self.rbt_PtBr.setChecked(True)
        self.rbt_PtBr.setObjectName("rbt_PtBr")
        self.rbg_Eng = QtWidgets.QRadioButton(self.gBox_Ling)
        self.rbg_Eng.setGeometry(QtCore.QRect(160, 25, 61, 18))
        self.rbg_Eng.setObjectName("rbg_Eng")
        self.gBox_Geral = QtWidgets.QGroupBox(self.gBox_Config)
        self.gBox_Geral.setGeometry(QtCore.QRect(10, 75, 240, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.gBox_Geral.setFont(font)
        self.gBox_Geral.setAutoFillBackground(False)
        self.gBox_Geral.setFlat(True)
        self.gBox_Geral.setObjectName("gBox_Geral")
        self.lbl_Format = QtWidgets.QLabel(self.gBox_Geral)
        self.lbl_Format.setGeometry(QtCore.QRect(20, 20, 101, 20))
        self.lbl_Format.setObjectName("lbl_Format")
        self.cBox_Datas = QtWidgets.QComboBox(self.gBox_Geral)
        self.cBox_Datas.setGeometry(QtCore.QRect(135, 20, 101, 22))
        self.cBox_Datas.setObjectName("cBox_Datas")
        self.cBox_Datas.addItem("")
        self.cBox_Datas.addItem("")
        self.cBox_Datas.addItem("")
        Gui.setCentralWidget(self.root)
        self.menubar = QtWidgets.QMenuBar(Gui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 22))
        self.menubar.setObjectName("menubar")
        Gui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Gui)
        self.statusbar.setObjectName("statusbar")
        Gui.setStatusBar(self.statusbar)

        self.retranslateUi(Gui)
        QtCore.QMetaObject.connectSlotsByName(Gui)

    def retranslateUi(self, Gui):
        _translate = QtCore.QCoreApplication.translate
        Gui.setWindowTitle(_translate("Gui", "MainWindow"))
        self.bt_Salvar.setText(_translate("Gui", "Salvar"))
        self.bt_Sair.setText(_translate("Gui", "Sair"))
        self.gBox_Config.setTitle(_translate("Gui", "Configurações"))
        self.gBox_Ling.setTitle(_translate("Gui", "Linguagem"))
        self.rbt_PtBr.setText(_translate("Gui", "Português-Brasil"))
        self.rbg_Eng.setText(_translate("Gui", "English"))
        self.gBox_Geral.setTitle(_translate("Gui", "Geral"))
        self.lbl_Format.setText(_translate("Gui", "Formato da data:"))
        self.cBox_Datas.setItemText(0, _translate("Gui", "dd/MM/aaaa"))
        self.cBox_Datas.setItemText(1, _translate("Gui", "MM/dd/aaaa"))
        self.cBox_Datas.setItemText(2, _translate("Gui", "aaaa/MM/dd"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gui = QtWidgets.QMainWindow()
    ui = Ui_Gui()
    ui.setupUi(Gui)
    Gui.show()
    sys.exit(app.exec_())
